//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated by the MSBuild CreateWin32MetadataFile target.

namespace InteropBuilder.Cli
{
    public static class Win32Metadata
    {
        public const string WinMdPath = @"E:\packages\nuget\microsoft.windows.sdk.win32metadata\59.0.13-preview";
    }
}
