namespace DirectN;

public enum WIN2D_GET_DEVICE_ASSOCIATION_TYPE
{
    WIN2D_GET_DEVICE_ASSOCIATION_TYPE_UNSPECIFIED = 0,
    WIN2D_GET_DEVICE_ASSOCIATION_TYPE_REALIZATION_DEVICE = 1,
    WIN2D_GET_DEVICE_ASSOCIATION_TYPE_CREATION_DEVICE = 2,
    WIN2D_GET_DEVICE_ASSOCIATION_TYPE_FORCE_DWORD = -1
}
